//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Data;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Mapping;

namespace cms.dbase.models
{
	/// <summary>
	/// Database       : DislyMVC
	/// Data Source    : chuvashia.com
	/// Server Version : 11.00.3000
	/// </summary>
	public partial class CMSdb : LinqToDB.Data.DataConnection
	{
		public ITable<_del_cms_sv_menu>               _del_cms_sv_menus               { get { return this.GetTable<_del_cms_sv_menu>(); } }
		public ITable<cms_log>                        cms_logs                        { get { return this.GetTable<cms_log>(); } }
		public ITable<cms_log_actions>                cms_log_actionss                { get { return this.GetTable<cms_log_actions>(); } }
		public ITable<cms_log_sections>               cms_log_sectionss               { get { return this.GetTable<cms_log_sections>(); } }
		public ITable<cms_menu>                       cms_menus                       { get { return this.GetTable<cms_menu>(); } }
		public ITable<cms_menu_group>                 cms_menu_groups                 { get { return this.GetTable<cms_menu_group>(); } }
		public ITable<cms_resolutions>                cms_resolutionss                { get { return this.GetTable<cms_resolutions>(); } }
		public ITable<cms_resolutions_templates>      cms_resolutions_templatess      { get { return this.GetTable<cms_resolutions_templates>(); } }
		public ITable<cms_sites>                      cms_sitess                      { get { return this.GetTable<cms_sites>(); } }
		public ITable<cms_sites_domains>              cms_sites_domainss              { get { return this.GetTable<cms_sites_domains>(); } }
		public ITable<cms_sv_log>                     cms_sv_logs                     { get { return this.GetTable<cms_sv_log>(); } }
		public ITable<cms_sv_log_users>               cms_sv_log_userss               { get { return this.GetTable<cms_sv_log_users>(); } }
		public ITable<cms_sv_resolutions>             cms_sv_resolutionss             { get { return this.GetTable<cms_sv_resolutions>(); } }
		public ITable<cms_sv_resolutions_templates>   cms_sv_resolutions_templatess   { get { return this.GetTable<cms_sv_resolutions_templates>(); } }
		public ITable<cms_sv_user_sites>              cms_sv_user_sitess              { get { return this.GetTable<cms_sv_user_sites>(); } }
		public ITable<cms_sv_users>                   cms_sv_userss                   { get { return this.GetTable<cms_sv_users>(); } }
		public ITable<cms_user_site_link>             cms_user_site_links             { get { return this.GetTable<cms_user_site_link>(); } }
		public ITable<cms_users>                      cms_userss                      { get { return this.GetTable<cms_users>(); } }
		public ITable<cms_users_group>                cms_users_groups                { get { return this.GetTable<cms_users_group>(); } }
		public ITable<content_departments>            content_departmentss            { get { return this.GetTable<content_departments>(); } }
		public ITable<content_events>                 content_eventss                 { get { return this.GetTable<content_events>(); } }
		public ITable<content_events_link>            content_events_links            { get { return this.GetTable<content_events_link>(); } }
		public ITable<content_materials>              content_materialss              { get { return this.GetTable<content_materials>(); } }
		public ITable<content_materials_link>         content_materials_links         { get { return this.GetTable<content_materials_link>(); } }
		public ITable<content_org_structure>          content_org_structures          { get { return this.GetTable<content_org_structure>(); } }
		public ITable<content_orgs>                   content_orgss                   { get { return this.GetTable<content_orgs>(); } }
		public ITable<content_people>                 content_peoples                 { get { return this.GetTable<content_people>(); } }
		public ITable<content_people_department_link> content_people_department_links { get { return this.GetTable<content_people_department_link>(); } }
		public ITable<content_people_org_link>        content_people_org_links        { get { return this.GetTable<content_people_org_link>(); } }
		public ITable<content_sitemap>                content_sitemaps                { get { return this.GetTable<content_sitemap>(); } }
		public ITable<front_modules>                  front_moduless                  { get { return this.GetTable<front_modules>(); } }
		public ITable<front_page_views>               front_page_viewss               { get { return this.GetTable<front_page_views>(); } }
		public ITable<front_section>                  front_sections                  { get { return this.GetTable<front_section>(); } }
		public ITable<front_site_section>             front_site_sections             { get { return this.GetTable<front_site_section>(); } }
		public ITable<front_sv_page_veiw>             front_sv_page_veiws             { get { return this.GetTable<front_sv_page_veiw>(); } }

		public CMSdb()
			: base("CMSdb")
		{
			InitDataContext();
		}

		public CMSdb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		#region Table Functions

		#region SF_SplitString

		[Sql.TableFunction(Schema="dbo", Name="SF_SplitString")]
		public ITable<SF_SplitStringResult> SF_SplitString(string @List, char? @Splitter)
		{
			return this.GetTable<SF_SplitStringResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(),
				@List,
				@Splitter);
		}

		public partial class SF_SplitStringResult
		{
			public int    ID { get; set; }
			public string V  { get; set; }
		}

		#endregion

		#region SF_UserResolutions

		[Sql.TableFunction(Schema="dbo", Name="SF_UserResolutions")]
		public ITable<SF_UserResolutionsResult> SF_UserResolutions(string @Url, Guid? @User)
		{
			return this.GetTable<SF_UserResolutionsResult>(this, (MethodInfo)MethodBase.GetCurrentMethod(),
				@Url,
				@User);
		}

		public partial class SF_UserResolutionsResult
		{
			public bool? B_Read   { get; set; }
			public bool? B_Write  { get; set; }
			public bool? B_Change { get; set; }
			public bool? B_Delete { get; set; }
		}

		#endregion

		#endregion

		#region FreeTextTable

		public class FreeTextKey<T>
		{
			public T   Key;
			public int Rank;
		}

		[FreeTextTableExpression]
		public ITable<FreeTextKey<TKey>> FreeTextTable<TTable,TKey>(string field, string text)
		{
			return this.GetTable<FreeTextKey<TKey>>(
				this,
				((MethodInfo)(MethodBase.GetCurrentMethod())).MakeGenericMethod(typeof(TTable), typeof(TKey)),
				field,
				text);
		}

		[FreeTextTableExpression]
		public ITable<FreeTextKey<TKey>> FreeTextTable<TTable,TKey>(Expression<Func<TTable,string>> fieldSelector, string text)
		{
			return this.GetTable<FreeTextKey<TKey>>(
				this,
				((MethodInfo)(MethodBase.GetCurrentMethod())).MakeGenericMethod(typeof(TTable), typeof(TKey)),
				fieldSelector,
				text);
		}

		#endregion
	}

	// View
	[Table(Schema="dbo", Name="_del_cms_sv_menu")]
	public partial class _del_cms_sv_menu
	{
		[Column, NotNull    ] public Guid   c_user_id   { get; set; } // uniqueidentifier
		[Column, NotNull    ] public int    n_permit    { get; set; } // int
		[Column, NotNull    ] public string c_title     { get; set; } // nvarchar(128)
		[Column,    Nullable] public string c_alias     { get; set; } // varchar(16)
		[Column,    Nullable] public string c_desc      { get; set; } // nvarchar(1024)
		[Column,    Nullable] public string c_class     { get; set; } // varchar(50)
		[Column,    Nullable] public string f_group     { get; set; } // varchar(16)
		[Column, NotNull    ] public bool   b_read      { get; set; } // bit
		[Column, NotNull    ] public bool   b_write     { get; set; } // bit
		[Column, NotNull    ] public bool   b_change    { get; set; } // bit
		[Column, NotNull    ] public bool   b_delete    { get; set; } // bit
		[Column, NotNull    ] public bool   b_importent { get; set; } // bit
	}

	[Table(Schema="dbo", Name="cms_log")]
	public partial class cms_log
	{
		[PrimaryKey, NotNull    ] public Guid     id          { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public Guid     f_page      { get; set; } // uniqueidentifier
		[Column,        Nullable] public string   c_page_name { get; set; } // nvarchar(512)
		[Column,        Nullable] public string   f_site      { get; set; } // varchar(64)
		[Column,        Nullable] public string   f_section   { get; set; } // varchar(64)
		[Column,     NotNull    ] public Guid     f_user      { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public DateTime d_date      { get; set; } // datetime
		[Column,     NotNull    ] public string   f_action    { get; set; } // varchar(32)
		[Column,     NotNull    ] public string   c_ip        { get; set; } // varchar(16)

		#region Associations

		/// <summary>
		/// FK_log_actions
		/// </summary>
		[Association(ThisKey="f_action", OtherKey="c_action", CanBeNull=false, KeyName="FK_log_actions", BackReferenceName="logactionss")]
		public cms_log_actions logactions { get; set; }

		/// <summary>
		/// FK_cms_log_sections
		/// </summary>
		[Association(ThisKey="f_section", OtherKey="c_alias", CanBeNull=true, KeyName="FK_cms_log_sections", BackReferenceName="cmslogsectionss")]
		public cms_log_sections cmslogsections { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_log_actions")]
	public partial class cms_log_actions
	{
		[PrimaryKey, NotNull] public string c_action      { get; set; } // varchar(32)
		[Column,     NotNull] public string c_action_name { get; set; } // varchar(256)

		#region Associations

		/// <summary>
		/// FK_log_actions_BackReference
		/// </summary>
		[Association(ThisKey="c_action", OtherKey="f_action", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_log> logactionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_log_sections")]
	public partial class cms_log_sections
	{
		[PrimaryKey, NotNull] public string c_alias        { get; set; } // varchar(64)
		[Column,     NotNull] public string c_section_name { get; set; } // varchar(64)

		#region Associations

		/// <summary>
		/// FK_cms_log_sections_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_section", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_log> cmslogsectionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_menu")]
	public partial class cms_menu
	{
		[PrimaryKey, NotNull    ] public Guid     id       { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public int      n_permit { get; set; } // int
		[Column,        Nullable] public string   c_alias  { get; set; } // varchar(16)
		[Column,     NotNull    ] public string   c_title  { get; set; } // nvarchar(128)
		[Column,        Nullable] public string   c_desc   { get; set; } // nvarchar(1024)
		[Column,     NotNull    ] public DateTime d_date   { get; set; } // datetime
		[Column,        Nullable] public string   c_class  { get; set; } // varchar(50)
		[Column,        Nullable] public string   f_group  { get; set; } // varchar(16)

		#region Associations

		/// <summary>
		/// FK_cms_menu_group
		/// </summary>
		[Association(ThisKey="f_group", OtherKey="c_alias", CanBeNull=true, KeyName="FK_cms_menu_group", BackReferenceName="cmsmenugroups")]
		public cms_menu_group cmsmenugroup { get; set; }

		/// <summary>
		/// fk_menu_template_resolutions_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_menu_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_resolutions_templates> fkmenutemplateresolutionss { get; set; }

		/// <summary>
		/// fk_menu_resolutions_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="c_menu_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_resolutions> fkmenuresolutionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_menu_group")]
	public partial class cms_menu_group
	{
		[Identity               ] public int    num     { get; set; } // int
		[Column,        Nullable] public string c_title { get; set; } // varchar(32)
		[PrimaryKey, NotNull    ] public string c_alias { get; set; } // varchar(16)

		#region Associations

		/// <summary>
		/// FK_cms_menu_group_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_menu> cmsmenugroups { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_resolutions")]
	public partial class cms_resolutions
	{
		[PrimaryKey, Identity] public int  id          { get; set; } // int
		[Column,     NotNull ] public Guid c_menu_id   { get; set; } // uniqueidentifier
		[Column,     NotNull ] public Guid c_user_id   { get; set; } // uniqueidentifier
		[Column,     NotNull ] public bool b_read      { get; set; } // bit
		[Column,     NotNull ] public bool b_write     { get; set; } // bit
		[Column,     NotNull ] public bool b_change    { get; set; } // bit
		[Column,     NotNull ] public bool b_delete    { get; set; } // bit
		[Column,     NotNull ] public bool b_importent { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_user_resolutions
		/// </summary>
		[Association(ThisKey="c_user_id", OtherKey="id", CanBeNull=false, KeyName="fk_user_resolutions", BackReferenceName="fkuserresolutionss")]
		public cms_users fkuserresolutions { get; set; }

		/// <summary>
		/// fk_menu_resolutions
		/// </summary>
		[Association(ThisKey="c_menu_id", OtherKey="id", CanBeNull=false, KeyName="fk_menu_resolutions", BackReferenceName="fkmenuresolutionss")]
		public cms_menu fkmenuresolutions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_resolutions_templates")]
	public partial class cms_resolutions_templates
	{
		[PrimaryKey, Identity] public int    id           { get; set; } // int
		[Column,     NotNull ] public Guid   f_menu_id    { get; set; } // uniqueidentifier
		[Column,     NotNull ] public string f_user_group { get; set; } // varchar(32)
		[Column,     NotNull ] public bool   b_read       { get; set; } // bit
		[Column,     NotNull ] public bool   b_write      { get; set; } // bit
		[Column,     NotNull ] public bool   b_change     { get; set; } // bit
		[Column,     NotNull ] public bool   b_delete     { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_user_group_resolutions
		/// </summary>
		[Association(ThisKey="f_user_group", OtherKey="c_alias", CanBeNull=false, KeyName="fk_user_group_resolutions", BackReferenceName="fkusergroupresolutionss")]
		public cms_users_group fkusergroupresolutions { get; set; }

		/// <summary>
		/// fk_menu_template_resolutions
		/// </summary>
		[Association(ThisKey="f_menu_id", OtherKey="id", CanBeNull=false, KeyName="fk_menu_template_resolutions", BackReferenceName="fkmenutemplateresolutionss")]
		public cms_menu fkmenutemplateresolutions { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_sites")]
	public partial class cms_sites
	{
		[Column,     NotNull    ] public Guid   id             { get; set; } // uniqueidentifier
		[PrimaryKey, NotNull    ] public string c_alias        { get; set; } // varchar(64)
		[Column,     NotNull    ] public string c_name         { get; set; } // nvarchar(512)
		[Column,        Nullable] public string c_adress       { get; set; } // varchar(512)
		[Column,        Nullable] public string c_phone        { get; set; } // varchar(64)
		[Column,        Nullable] public string c_fax          { get; set; } // varchar(64)
		[Column,        Nullable] public string c_email        { get; set; } // varchar(64)
		[Column,        Nullable] public string c_url          { get; set; } // varchar(128)
		[Column,        Nullable] public string c_worktime     { get; set; } // varchar(512)
		[Column,        Nullable] public string c_logo         { get; set; } // varchar(512)
		[Column,        Nullable] public Guid?  f_content      { get; set; } // uniqueidentifier
		[Column,        Nullable] public string c_content_type { get; set; } // varchar(64)

		#region Associations

		/// <summary>
		/// fk_sites_page_views_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_page_views> fksitespageviewss { get; set; }

		/// <summary>
		/// fk_sites_domains_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_sites_domains> fksitesdomainss { get; set; }

		/// <summary>
		/// fk_content_sitemap_from_sites_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_sitemap> fkcontentsitemapfromsitess { get; set; }

		/// <summary>
		/// fk_link_site_to_user_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_user_site_link> fklinksitetousers { get; set; }

		/// <summary>
		/// FK_site_front_section_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_site", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_site_section> sitefrontsections { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_sites_domains")]
	public partial class cms_sites_domains
	{
		[Identity           ] public int    num      { get; set; } // int
		[Column,     NotNull] public Guid   id       { get; set; } // uniqueidentifier
		[Column,     NotNull] public string f_site   { get; set; } // varchar(64)
		[PrimaryKey, NotNull] public string c_domain { get; set; } // varchar(256)

		#region Associations

		/// <summary>
		/// fk_sites_domains
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="fk_sites_domains", BackReferenceName="fksitesdomainss")]
		public cms_sites fksitesdomains { get; set; }

		#endregion
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_log")]
	public partial class cms_sv_log
	{
		[Column, NotNull    ] public Guid     id            { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid     f_user        { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   c_surname     { get; set; } // nvarchar(128)
		[Column, NotNull    ] public string   c_name        { get; set; } // nvarchar(128)
		[Column,    Nullable] public string   c_patronymic  { get; set; } // nvarchar(128)
		[Column,    Nullable] public string   c_email       { get; set; } // nvarchar(128)
		[Column, NotNull    ] public DateTime d_date        { get; set; } // datetime
		[Column, NotNull    ] public string   f_action      { get; set; } // varchar(32)
		[Column, NotNull    ] public string   c_action_name { get; set; } // varchar(256)
		[Column, NotNull    ] public Guid     f_page        { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   c_ip          { get; set; } // varchar(16)
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_log_users")]
	public partial class cms_sv_log_users
	{
		[Column, NotNull    ] public DateTime d_date         { get; set; } // datetime
		[Column, NotNull    ] public string   f_action       { get; set; } // varchar(32)
		[Column, NotNull    ] public string   c_action_name  { get; set; } // varchar(256)
		[Column,    Nullable] public string   f_site         { get; set; } // varchar(64)
		[Column,    Nullable] public string   f_section      { get; set; } // varchar(64)
		[Column, NotNull    ] public string   c_section_name { get; set; } // varchar(64)
		[Column, NotNull    ] public Guid     f_page         { get; set; } // uniqueidentifier
		[Column,    Nullable] public string   c_page_name    { get; set; } // nvarchar(512)
		[Column, NotNull    ] public Guid     f_user         { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string   c_ip           { get; set; } // varchar(16)
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_resolutions")]
	public partial class cms_sv_resolutions
	{
		[Column, NotNull    ] public Guid   c_menu_id    { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string c_title      { get; set; } // nvarchar(128)
		[Column,    Nullable] public string f_group      { get; set; } // varchar(16)
		[Column, NotNull    ] public int    n_permit     { get; set; } // int
		[Column, NotNull    ] public Guid   c_user_id    { get; set; } // uniqueidentifier
		[Column,    Nullable] public string F_UserGroup  { get; set; } // varchar(32)
		[Column, NotNull    ] public string c_surname    { get; set; } // nvarchar(128)
		[Column, NotNull    ] public string c_name       { get; set; } // nvarchar(128)
		[Column,    Nullable] public string c_patronymic { get; set; } // nvarchar(128)
		[Column,    Nullable] public string c_email      { get; set; } // nvarchar(128)
		[Column, NotNull    ] public bool   b_read       { get; set; } // bit
		[Column, NotNull    ] public bool   b_write      { get; set; } // bit
		[Column, NotNull    ] public bool   b_change     { get; set; } // bit
		[Column, NotNull    ] public bool   b_delete     { get; set; } // bit
		[Column, NotNull    ] public bool   b_importent  { get; set; } // bit
		[Column,    Nullable] public string c_class      { get; set; } // varchar(50)
		[Column,    Nullable] public string c_alias      { get; set; } // varchar(16)
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_resolutions_templates")]
	public partial class cms_sv_resolutions_templates
	{
		[Column, NotNull    ] public string c_title           { get; set; } // nvarchar(128)
		[Column, NotNull    ] public int    n_permit          { get; set; } // int
		[Column,    Nullable] public string f_group           { get; set; } // varchar(16)
		[Column, NotNull    ] public string c_user_group_name { get; set; } // varchar(128)
		[Column, NotNull    ] public bool   b_read            { get; set; } // bit
		[Column, NotNull    ] public bool   b_write           { get; set; } // bit
		[Column, NotNull    ] public bool   b_change          { get; set; } // bit
		[Column, NotNull    ] public bool   b_delete          { get; set; } // bit
		[Column, NotNull    ] public string f_user_group      { get; set; } // varchar(32)
		[Column, NotNull    ] public Guid   id                { get; set; } // uniqueidentifier
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_user_sites")]
	public partial class cms_sv_user_sites
	{
		[Column, NotNull] public Guid   f_user { get; set; } // uniqueidentifier
		[Column, NotNull] public string f_site { get; set; } // varchar(64)
		[Column, NotNull] public string c_name { get; set; } // nvarchar(512)
	}

	// View
	[Table(Schema="dbo", Name="cms_sv_users")]
	public partial class cms_sv_users
	{
		[Column, NotNull    ] public Guid      id           { get; set; } // uniqueidentifier
		[Column,    Nullable] public string    c_email      { get; set; } // nvarchar(128)
		[Column,    Nullable] public string    c_salt       { get; set; } // nvarchar(32)
		[Column,    Nullable] public string    c_hash       { get; set; } // nvarchar(128)
		[Column,    Nullable] public string    f_group      { get; set; } // varchar(32)
		[Column, NotNull    ] public string    f_group_name { get; set; } // varchar(128)
		[Column,    Nullable] public string    c_post       { get; set; } // nvarchar(1024)
		[Column, NotNull    ] public string    c_surname    { get; set; } // nvarchar(128)
		[Column, NotNull    ] public string    c_name       { get; set; } // nvarchar(128)
		[Column,    Nullable] public string    c_patronymic { get; set; } // nvarchar(128)
		[Column,    Nullable] public DateTime? d_birthday   { get; set; } // datetime
		[Column, NotNull    ] public bool      b_sex        { get; set; } // bit
		[Column,    Nullable] public string    c_photo      { get; set; } // nvarchar(512)
		[Column,    Nullable] public string    c_adres      { get; set; } // nvarchar(1024)
		[Column,    Nullable] public string    c_phone      { get; set; } // nvarchar(32)
		[Column,    Nullable] public string    c_mobile     { get; set; } // nvarchar(32)
		[Column,    Nullable] public string    c_contacts   { get; set; } // nvarchar(max)
		[Column, NotNull    ] public bool      b_disabled   { get; set; } // bit
	}

	[Table(Schema="dbo", Name="cms_user_site_link")]
	public partial class cms_user_site_link
	{
		[Column, NotNull] public Guid   f_user { get; set; } // uniqueidentifier
		[Column, NotNull] public string f_site { get; set; } // varchar(64)

		#region Associations

		/// <summary>
		/// fk_link_site_to_user
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="fk_link_site_to_user", BackReferenceName="fklinksitetousers")]
		public cms_sites fklinksitetouser { get; set; }

		/// <summary>
		/// fk_link_user_to_site
		/// </summary>
		[Association(ThisKey="f_user", OtherKey="id", CanBeNull=false, KeyName="fk_link_user_to_site", BackReferenceName="fklinkusertosites")]
		public cms_users fklinkusertosite { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_users")]
	public partial class cms_users
	{
		[PrimaryKey, NotNull    ] public Guid      id                 { get; set; } // uniqueidentifier
		[Column,        Nullable] public string    c_email            { get; set; } // nvarchar(128)
		[Column,        Nullable] public string    c_salt             { get; set; } // nvarchar(32)
		[Column,        Nullable] public string    c_hash             { get; set; } // nvarchar(128)
		[Column,        Nullable] public Guid?     с_change_pass_code { get; set; } // uniqueidentifier
		[Column,        Nullable] public string    f_group            { get; set; } // varchar(32)
		[Column,        Nullable] public string    c_post             { get; set; } // nvarchar(1024)
		[Column,     NotNull    ] public string    c_surname          { get; set; } // nvarchar(128)
		[Column,     NotNull    ] public string    c_name             { get; set; } // nvarchar(128)
		[Column,        Nullable] public string    c_patronymic       { get; set; } // nvarchar(128)
		[Column,        Nullable] public DateTime? d_birthday         { get; set; } // datetime
		[Column,     NotNull    ] public bool      b_sex              { get; set; } // bit
		[Column,        Nullable] public string    c_photo            { get; set; } // nvarchar(512)
		[Column,        Nullable] public string    c_adres            { get; set; } // nvarchar(1024)
		[Column,        Nullable] public string    c_phone            { get; set; } // nvarchar(32)
		[Column,        Nullable] public string    c_mobile           { get; set; } // nvarchar(32)
		[Column,        Nullable] public string    c_contacts         { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public DateTime  d_try_login        { get; set; } // datetime
		[Column,     NotNull    ] public int       n_error_count      { get; set; } // int
		[Column,     NotNull    ] public bool      b_disabled         { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_users_group
		/// </summary>
		[Association(ThisKey="f_group", OtherKey="c_alias", CanBeNull=true, KeyName="fk_users_group", BackReferenceName="fkusersgroups")]
		public cms_users_group fkusersgroup { get; set; }

		/// <summary>
		/// fk_user_resolutions_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="c_user_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_resolutions> fkuserresolutionss { get; set; }

		/// <summary>
		/// fk_link_user_to_site_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_user", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_user_site_link> fklinkusertosites { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="cms_users_group")]
	public partial class cms_users_group
	{
		[Column,     NotNull] public Guid   id      { get; set; } // uniqueidentifier
		[Column,     NotNull] public string c_title { get; set; } // varchar(128)
		[PrimaryKey, NotNull] public string c_alias { get; set; } // varchar(32)

		#region Associations

		/// <summary>
		/// fk_users_group_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_users> fkusersgroups { get; set; }

		/// <summary>
		/// fk_user_group_resolutions_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_user_group", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<cms_resolutions_templates> fkusergroupresolutionss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_departments")]
	public partial class content_departments
	{
		[PrimaryKey, NotNull] public Guid   id          { get; set; } // uniqueidentifier
		[Column,     NotNull] public Guid   f_structure { get; set; } // uniqueidentifier
		[Column,     NotNull] public string c_title     { get; set; } // varchar(1024)

		#region Associations

		/// <summary>
		/// FK_content_org_structure_departments
		/// </summary>
		[Association(ThisKey="f_structure", OtherKey="id", CanBeNull=false, KeyName="FK_content_org_structure_departments", BackReferenceName="contentorgstructuredepartmentss")]
		public content_org_structure contentorgstructuredepartments { get; set; }

		/// <summary>
		/// fk_content_department_people_link_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_department", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_people_department_link> fkcontentdepartmentpeoplelinks { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_events")]
	public partial class content_events
	{
		[PrimaryKey, NotNull    ] public Guid      id          { get; set; } // uniqueidentifier
		[Identity               ] public int       num         { get; set; } // int
		[Column,     NotNull    ] public DateTime  d_date      { get; set; } // datetime
		[Column,        Nullable] public DateTime? d_date_end  { get; set; } // datetime
		[Column,     NotNull    ] public bool      b_annually  { get; set; } // bit
		[Column,     NotNull    ] public string    c_title     { get; set; } // varchar(512)
		[Column,        Nullable] public string    c_preview   { get; set; } // varchar(1024)
		[Column,        Nullable] public string    c_text      { get; set; } // varchar(512)
		[Column,        Nullable] public string    c_place     { get; set; } // varchar(512)
		[Column,        Nullable] public string    c_organizer { get; set; } // varchar(1024)
		[Column,        Nullable] public string    c_url       { get; set; } // varchar(1024)
		[Column,        Nullable] public string    c_url_name  { get; set; } // varchar(512)
		[Column,        Nullable] public string    c_alias     { get; set; } // varchar(512)
		[Column,        Nullable] public string    c_desc      { get; set; } // varchar(1024)
		[Column,        Nullable] public string    c_keyw      { get; set; } // varchar(512)
		[Column,     NotNull    ] public bool      b_disabled  { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_content_events_link_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_event", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_events_link> fkcontenteventslinks { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_events_link")]
	public partial class content_events_link
	{
		[Column, NotNull    ] public Guid   f_event     { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid   f_link_id   { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string f_link_type { get; set; } // varchar(16)
		[Column,    Nullable] public string c_group     { get; set; } // varchar(32)

		#region Associations

		/// <summary>
		/// fk_content_events_link
		/// </summary>
		[Association(ThisKey="f_event", OtherKey="id", CanBeNull=false, KeyName="fk_content_events_link", BackReferenceName="fkcontenteventslinks")]
		public content_events fkcontenteventslink { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_materials")]
	public partial class content_materials
	{
		[PrimaryKey, NotNull    ] public Guid     id          { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public DateTime d_date      { get; set; } // datetime
		[Column,     NotNull    ] public string   c_title     { get; set; } // varchar(512)
		[Column,        Nullable] public string   c_preview   { get; set; } // varchar(512)
		[Column,        Nullable] public string   c_text      { get; set; } // varchar(max)
		[Column,        Nullable] public string   c_url       { get; set; } // varchar(1024)
		[Column,        Nullable] public string   c_url_name  { get; set; } // varchar(512)
		[Column,        Nullable] public string   c_desc      { get; set; } // varchar(1024)
		[Column,        Nullable] public string   c_keyw      { get; set; } // varchar(512)
		[Column,     NotNull    ] public int      n_year      { get; set; } // int
		[Column,     NotNull    ] public int      n_month     { get; set; } // int
		[Column,     NotNull    ] public int      n_day       { get; set; } // int
		[Column,     NotNull    ] public string   c_alias     { get; set; } // varchar(512)
		[Column,     NotNull    ] public bool     b_disabled  { get; set; } // bit
		[Column,     NotNull    ] public bool     b_important { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_content_materials_link_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_material", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_materials_link> fkcontentmaterialslinks { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_materials_link")]
	public partial class content_materials_link
	{
		[Column, NotNull    ] public Guid   f_material  { get; set; } // uniqueidentifier
		[Column, NotNull    ] public Guid   f_link_id   { get; set; } // uniqueidentifier
		[Column, NotNull    ] public string f_link_type { get; set; } // varchar(16)
		[Column,    Nullable] public string c_group     { get; set; } // varchar(32)

		#region Associations

		/// <summary>
		/// fk_content_materials_link
		/// </summary>
		[Association(ThisKey="f_material", OtherKey="id", CanBeNull=false, KeyName="fk_content_materials_link", BackReferenceName="fkcontentmaterialslinks")]
		public content_materials fkcontentmaterialslink { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_org_structure")]
	public partial class content_org_structure
	{
		[PrimaryKey, NotNull    ] public Guid    id                { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public Guid    f_ord             { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string  c_title           { get; set; } // nvarchar(512)
		[Column,        Nullable] public string  c_adress          { get; set; } // nvarchar(512)
		[Column,        Nullable] public double? n_geopoint_x      { get; set; } // float
		[Column,        Nullable] public double? n_geopoint_y      { get; set; } // float
		[Column,        Nullable] public string  c_phone           { get; set; } // varchar(64)
		[Column,        Nullable] public string  c_phone_reception { get; set; } // varchar(64)
		[Column,        Nullable] public string  c_fax             { get; set; } // varchar(64)
		[Column,        Nullable] public string  c_email           { get; set; } // varchar(128)
		[Column,        Nullable] public string  c_routes          { get; set; } // nvarchar(max)
		[Column,        Nullable] public string  c_schedule        { get; set; } // nvarchar(max)
		[Column,        Nullable] public string  c_director_post   { get; set; } // varchar(64)
		[Column,        Nullable] public Guid?   f_director        { get; set; } // uniqueidentifier

		#region Associations

		/// <summary>
		/// FK_content_orgs_structure
		/// </summary>
		[Association(ThisKey="f_ord", OtherKey="id", CanBeNull=false, KeyName="FK_content_orgs_structure", BackReferenceName="contentorgsstructures")]
		public content_orgs contentorgsstructure { get; set; }

		/// <summary>
		/// FK_content_org_structure_departments_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_structure", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_departments> contentorgstructuredepartmentss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_orgs")]
	public partial class content_orgs
	{
		[PrimaryKey, NotNull] public Guid   id      { get; set; } // uniqueidentifier
		[Column,     NotNull] public string c_title { get; set; } // nvarchar(512)

		#region Associations

		/// <summary>
		/// FK_content_orgs_structure_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_ord", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_org_structure> contentorgsstructures { get; set; }

		/// <summary>
		/// FK_content_org_people_link_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_org", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_people_org_link> contentorgpeoplelinks { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_people")]
	public partial class content_people
	{
		[PrimaryKey, NotNull    ] public Guid   id           { get; set; } // uniqueidentifier
		[Column,        Nullable] public string c_surname    { get; set; } // varchar(64)
		[Column,        Nullable] public string c_name       { get; set; } // varchar(64)
		[Column,        Nullable] public string c_patronymic { get; set; } // varchar(64)

		#region Associations

		/// <summary>
		/// fk_content_people_org_link_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_people", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_people_org_link> fkcontentpeopleorglinks { get; set; }

		/// <summary>
		/// fk_content_people_department_link_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_people", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<content_people_department_link> fkcontentpeopledepartmentlinks { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_people_department_link")]
	public partial class content_people_department_link
	{
		[Column, NotNull] public Guid f_department { get; set; } // uniqueidentifier
		[Column, NotNull] public Guid f_people     { get; set; } // uniqueidentifier

		#region Associations

		/// <summary>
		/// fk_content_people_department_link
		/// </summary>
		[Association(ThisKey="f_people", OtherKey="id", CanBeNull=false, KeyName="fk_content_people_department_link", BackReferenceName="fkcontentpeopledepartmentlinks")]
		public content_people fkcontentpeopledepartmentlink { get; set; }

		/// <summary>
		/// fk_content_department_people_link
		/// </summary>
		[Association(ThisKey="f_department", OtherKey="id", CanBeNull=false, KeyName="fk_content_department_people_link", BackReferenceName="fkcontentdepartmentpeoplelinks")]
		public content_departments fkcontentdepartmentpeoplelink { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_people_org_link")]
	public partial class content_people_org_link
	{
		[Column, NotNull] public Guid f_org    { get; set; } // uniqueidentifier
		[Column, NotNull] public Guid f_people { get; set; } // uniqueidentifier

		#region Associations

		/// <summary>
		/// fk_content_people_org_link
		/// </summary>
		[Association(ThisKey="f_people", OtherKey="id", CanBeNull=false, KeyName="fk_content_people_org_link", BackReferenceName="fkcontentpeopleorglinks")]
		public content_people fkcontentpeopleorglink { get; set; }

		/// <summary>
		/// FK_content_org_people_link
		/// </summary>
		[Association(ThisKey="f_org", OtherKey="id", CanBeNull=false, KeyName="FK_content_org_people_link", BackReferenceName="contentorgpeoplelinks")]
		public content_orgs contentorgpeoplelink { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="content_sitemap")]
	public partial class content_sitemap
	{
		[PrimaryKey, NotNull    ] public Guid   id              { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public string f_site          { get; set; } // varchar(64)
		[Column,     NotNull    ] public string f_front_section { get; set; } // nvarchar(16)
		[Column,     NotNull    ] public string c_path          { get; set; } // varchar(1024)
		[Column,        Nullable] public string c_alias         { get; set; } // varchar(64)
		[Column,        Nullable] public string c_title         { get; set; } // nvarchar(256)
		[Column,        Nullable] public string c_preview       { get; set; } // varchar(1024)
		[Column,        Nullable] public string c_url           { get; set; } // varchar(1024)
		[Column,        Nullable] public string c_text          { get; set; } // nvarchar(max)
		[Column,        Nullable] public string c_desc          { get; set; } // nvarchar(1024)
		[Column,        Nullable] public string c_keyw          { get; set; } // nvarchar(512)
		[Column,     NotNull    ] public bool   b_disabled      { get; set; } // bit
		[Column,     NotNull    ] public bool   b_disabled_menu { get; set; } // bit

		#region Associations

		/// <summary>
		/// fk_content_sitemap_from_sites
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="fk_content_sitemap_from_sites", BackReferenceName="fkcontentsitemapfromsitess")]
		public cms_sites fkcontentsitemapfromsites { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="front_modules")]
	public partial class front_modules
	{
		[PrimaryKey, NotNull] public Guid   id           { get; set; } // uniqueidentifier
		[Column,     NotNull] public string c_name       { get; set; } // nvarchar(512)
		[Column,     NotNull] public string f_size       { get; set; } // varchar(16)
		[Column,     NotNull] public string f_type       { get; set; } // varchar(16)
		[Column,     NotNull] public string c_alias      { get; set; } // nvarchar(16)
		[Column,     NotNull] public string c_controller { get; set; } // nvarchar(32)
		[Column,     NotNull] public string c_action     { get; set; } // nvarchar(32)
		[Column,     NotNull] public string c_url        { get; set; } // nvarchar(512)

		#region Associations

		/// <summary>
		/// FK_module_section
		/// </summary>
		[Association(ThisKey="f_type", OtherKey="c_alias", CanBeNull=false, KeyName="FK_module_section", BackReferenceName="modulesections")]
		public front_section modulesection { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="front_page_views")]
	public partial class front_page_views
	{
		[PrimaryKey, NotNull    ] public Guid   id          { get; set; } // uniqueidentifier
		[Column,        Nullable] public string f_site      { get; set; } // varchar(64)
		[Column,     NotNull    ] public string c_title     { get; set; } // nvarchar(256)
		[Column,        Nullable] public string f_pege_type { get; set; } // varchar(16)
		[Column,     NotNull    ] public string c_url       { get; set; } // varchar(1024)

		#region Associations

		/// <summary>
		/// fk_sites_page_views
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=true, KeyName="fk_sites_page_views", BackReferenceName="fksitespageviewss")]
		public cms_sites fksitespageviews { get; set; }

		/// <summary>
		/// FK_site_front_section_page_views_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="f_page_view", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_site_section> sitefrontsectionpageviewss { get; set; }

		/// <summary>
		/// FK_front_section_default_page_views_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="c_default_view", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_section> frontsectiondefaultpageviewss { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="front_section")]
	public partial class front_section
	{
		[Column,     NotNull] public Guid   id             { get; set; } // uniqueidentifier
		[Column,     NotNull] public string c_name         { get; set; } // varchar(128)
		[PrimaryKey, NotNull] public string c_alias        { get; set; } // varchar(16)
		[Column,     NotNull] public Guid   c_default_view { get; set; } // uniqueidentifier

		#region Associations

		/// <summary>
		/// FK_front_section_default_page_views
		/// </summary>
		[Association(ThisKey="c_default_view", OtherKey="id", CanBeNull=false, KeyName="FK_front_section_default_page_views", BackReferenceName="frontsectiondefaultpageviewss")]
		public front_page_views frontsectiondefaultpageviews { get; set; }

		/// <summary>
		/// FK_module_section_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_type", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_modules> modulesections { get; set; }

		/// <summary>
		/// FK_front_section_site_BackReference
		/// </summary>
		[Association(ThisKey="c_alias", OtherKey="f_front_section", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<front_site_section> frontsectionsites { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="front_site_section")]
	public partial class front_site_section
	{
		[Column, NotNull] public string f_site          { get; set; } // varchar(64)
		[Column, NotNull] public string f_front_section { get; set; } // varchar(16)
		[Column, NotNull] public Guid   f_page_view     { get; set; } // uniqueidentifier

		#region Associations

		/// <summary>
		/// FK_site_front_section_page_views
		/// </summary>
		[Association(ThisKey="f_page_view", OtherKey="id", CanBeNull=false, KeyName="FK_site_front_section_page_views", BackReferenceName="sitefrontsectionpageviewss")]
		public front_page_views sitefrontsectionpageviews { get; set; }

		/// <summary>
		/// FK_front_section_site
		/// </summary>
		[Association(ThisKey="f_front_section", OtherKey="c_alias", CanBeNull=false, KeyName="FK_front_section_site", BackReferenceName="frontsectionsites")]
		public front_section frontsectionsite { get; set; }

		/// <summary>
		/// FK_site_front_section
		/// </summary>
		[Association(ThisKey="f_site", OtherKey="c_alias", CanBeNull=false, KeyName="FK_site_front_section", BackReferenceName="sitefrontsections")]
		public cms_sites sitefrontsection { get; set; }

		#endregion
	}

	// View
	[Table(Schema="dbo", Name="front_sv_page_veiw")]
	public partial class front_sv_page_veiw
	{
		[Column,    Nullable] public string f_site      { get; set; } // varchar(64)
		[Column, NotNull    ] public string c_title     { get; set; } // nvarchar(256)
		[Column,    Nullable] public string f_pege_type { get; set; } // varchar(16)
		[Column, NotNull    ] public string c_name      { get; set; } // varchar(128)
		[Column, NotNull    ] public string c_url       { get; set; } // varchar(1024)
	}

	public static partial class CMSdbStoredProcedures
	{
		#region sp_alterdiagram

		public static int sp_alterdiagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32),
				new DataParameter("@version",     @version,     DataType.Int32),
				new DataParameter("@definition",  @definition,  DataType.VarBinary));
		}

		#endregion

		#region sp_creatediagram

		public static int sp_creatediagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32),
				new DataParameter("@version",     @version,     DataType.Int32),
				new DataParameter("@definition",  @definition,  DataType.VarBinary));
		}

		#endregion

		#region sp_dropdiagram

		public static int sp_dropdiagram(this DataConnection dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32));
		}

		#endregion

		#region sp_helpdiagramdefinition

		public static IEnumerable<sp_helpdiagramdefinitionResult> sp_helpdiagramdefinition(this DataConnection dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.QueryProc<sp_helpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32));
		}

		public partial class sp_helpdiagramdefinitionResult
		{
			public int?   version    { get; set; }
			public byte[] definition { get; set; }
		}

		#endregion

		#region sp_helpdiagrams

		public static IEnumerable<sp_helpdiagramsResult> sp_helpdiagrams(this DataConnection dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.QueryProc<sp_helpdiagramsResult>("[dbo].[sp_helpdiagrams]",
				new DataParameter("@diagramname", @diagramname, DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    DataType.Int32));
		}

		public partial class sp_helpdiagramsResult
		{
			public string Database { get; set; }
			public string Name     { get; set; }
			public int    ID       { get; set; }
			public string Owner    { get; set; }
			public int    OwnerID  { get; set; }
		}

		#endregion

		#region sp_renamediagram

		public static int sp_renamediagram(this DataConnection dataConnection, string @diagramname, int? @owner_id, string @new_diagramname)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]",
				new DataParameter("@diagramname",     @diagramname,     DataType.NVarChar),
				new DataParameter("@owner_id",        @owner_id,        DataType.Int32),
				new DataParameter("@new_diagramname", @new_diagramname, DataType.NVarChar));
		}

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region fn_diagramobjects

		[Sql.Function(Name="dbo.fn_diagramobjects", ServerSideOnly=true)]
		public static int? fn_diagramobjects()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static cms_log Find(this ITable<cms_log> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_log_actions Find(this ITable<cms_log_actions> table, string c_action)
		{
			return table.FirstOrDefault(t =>
				t.c_action == c_action);
		}

		public static cms_log_sections Find(this ITable<cms_log_sections> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static cms_menu Find(this ITable<cms_menu> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_menu_group Find(this ITable<cms_menu_group> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static cms_resolutions Find(this ITable<cms_resolutions> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_resolutions_templates Find(this ITable<cms_resolutions_templates> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_sites Find(this ITable<cms_sites> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static cms_sites_domains Find(this ITable<cms_sites_domains> table, string c_domain)
		{
			return table.FirstOrDefault(t =>
				t.c_domain == c_domain);
		}

		public static cms_users Find(this ITable<cms_users> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static cms_users_group Find(this ITable<cms_users_group> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}

		public static content_departments Find(this ITable<content_departments> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_events Find(this ITable<content_events> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_materials Find(this ITable<content_materials> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_org_structure Find(this ITable<content_org_structure> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_orgs Find(this ITable<content_orgs> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_people Find(this ITable<content_people> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static content_sitemap Find(this ITable<content_sitemap> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static front_modules Find(this ITable<front_modules> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static front_page_views Find(this ITable<front_page_views> table, Guid id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static front_section Find(this ITable<front_section> table, string c_alias)
		{
			return table.FirstOrDefault(t =>
				t.c_alias == c_alias);
		}
	}
}
